// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models.DB;

public partial class DingContext : DbContext
{
    public DingContext(DbContextOptions<DingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<User> User { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Email);

            entity.Property(e => e.Email)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasComment("信箱");
            entity.Property(e => e.Age).HasComment("年齡");
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("城市");
            entity.Property(e => e.Gender).HasComment("性別(0:女、1:男)");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("姓名");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("密碼");
            entity.Property(e => e.Region)
                .IsRequired()
                .HasMaxLength(20)
                .HasComment("省份");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}